---
# handlers file for test-role
- name: start mongodb
  service: name=mongodb state=started
#restarted will always bounce the service. reloaded will always reload.
- name: reload mongodb
  service: name=mongodb state=reloaded

