---
- hosts: servers
  remote_user: ubuntu
  tasks:
   - name: Enable root access
#It is almost exactly like the command module but runs the command through a shell (/bin/sh) on the remote node
     shell: sudo cp ~/.ssh/authorized_keys /root/.ssh/
