Script started on Mon 04 Apr 2016 08:30:23 PM EDT

PLAY ***************************************************************************

TASK [setup] *******************************************************************
[0;32mok: [10.0.6.80][0m

TASK [mongodb : Import public key] *********************************************
[0;32mok: [10.0.6.80][0m

TASK [mongodb : Add MongoDB repo] **********************************************
[0;32mok: [10.0.6.80][0m

TASK [mongodb : Install MongoDB] ***********************************************
[0;32mok: [10.0.6.80][0m

TASK [mongodb : file] **********************************************************
[0;32mok: [10.0.6.80][0m

TASK [mongodb : force handlers] ************************************************
[0;33mchanged: [10.0.6.80][0m

TASK [mongodb : template] ******************************************************
[0;32mok: [10.0.6.80][0m

RUNNING HANDLER [mongodb : start mongodb] **************************************
[0;32mok: [10.0.6.80][0m

PLAY RECAP *********************************************************************
[0;33m10.0.6.80[0m                  : [0;32mok[0m[0;32m=[0m[0;32m8[0m    [0;33mchanged[0m[0;33m=[0m[0;33m1[0m    unreachable=0    failed=0   


Script done on Mon 04 Apr 2016 08:30:51 PM EDT
Script started on Mon 04 Apr 2016 08:31:06 PM EDT
[0;32m10.0.6.80 | SUCCESS | rc=0 >>
● mongodb.service - mongodb
   Loaded: loaded (/lib/systemd/system/mongodb.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2016-04-04 14:56:02 UTC; 9h ago
 Main PID: 30978 (mongod)
   CGroup: /system.slice/mongodb.service
           └─30978 /usr/bin/mongod --quiet --config /etc/mongod.conf

Apr 04 14:56:02 hw3-manashree systemd[1]: Started mongodb.
[0m

Script done on Mon 04 Apr 2016 08:31:10 PM EDT
